### ISSUE TITLE
Compile warning when trying to use with STM32F1 boards

### ISSUE THREAD

**Issue by leecyrille** [MichaelUray/muTimer#6]
`
WARNING: library muTimer claims to run on avr, esp8266, esp32 architecture(s) and may be incompatible with your current board which runs on STM32F1 architecture(s).
Sketch uses 11692 bytes (10%) of program storage space. Maximum is 108000 bytes.
Global variables use 1544 bytes (9%) of dynamic memory, leaving 15456 bytes for local variables. Maximum is 17000 bytes.
`

The following warning is presented when trying to use MuTimer library with STM32 boards. Is there any reason this won't work with STM32 boards?

**Comment by MichaelUray** [comment]
This is just a warning, that the library is not specifically tested for your platform.

This forum entry explains it.
https://forum.arduino.cc/t/warning-library-liquidcrystal_i2c-1-1-2-claims-to-run-on-avr-architecture-s/556271

**Comment by leecyrille** [comment]
This works fine on the STM32 with Roger Melbournes STM32 framework FYI.
